### ISSUE TITLE
'triton ls' alias for insts

### ISSUE THREAD

**Issue by bahamat** [joyent/node-triton#45] opened 2015-10-14 20:35 UTC
Similar to #44.

**Comment by bahamat** [comment] 2015-10-14 20:37
If `ls` is going to be added, might be worth adding `list` as well, although I would argue `ps` (à la docker) is going too far.

**Comment by misterbisson** [comment] 2015-10-14 20:38
But if people expect `ps` from Docker...

**Comment by jclulow** [comment] 2015-10-14 20:39
We will absolutely not be continuing the `ps` _lunacy_.

**Comment by trentm** [comment] 2015-10-14 21:12
Let's leave `ps` to a `jocker ps` command. ;)

**Comment by trentm** [comment] 2015-10-14 21:13
This ticket is a dupe of  #34

**Closed by trentm** 2015-10-14 21:13 UTC
