### ISSUE TITLE
Error while attempting to create a profile on Cygwin

### ISSUE THREAD

**Issue by xer0x** [joyent/node-triton#84] opened 2016-01-28 16:16 UTC
`triton` hits a few snags on Windows. Here is another one when using Cygwin:

```
$ triton profile create
triton profile: error (Usage): cannot interactively create profile: stdin is not a TTY
```

This gets a little further than https://github.com/joyent/node-triton/issues/83. I haven't tried anything else yet.

**Comment by trentm** [comment] 2016-01-28 21:44
Duplicate of #83. Fixed now.

**Closed by trentm** 2016-01-28 21:44 UTC

**Comment by BobDickinson** [comment] 2016-07-12 20:09
$ triton profile create
    triton profile create: error (Usage): cannot interactively create profile: stdin is not a TTY
    usage: triton profile create [OPTIONS]
    $ triton --version
    triton 4.13.0

This bug seems pretty alive and well to me (using current version of babun, which wraps Cygwin)
